# Generated by Django 5.2.1 on 2025-06-05 19:08

from django.db import migrations


def create_initial_rooms(apps, schema_editor):
    Room = apps.get_model('api', 'Room')
    
    initial_rooms = [
    {
        'number': '1',
        'room_type': 'standard',
        'capacity': 2,
        'price_per_night': 2500,
        'description': 'Стандартный номер с видом на город'
    },
    ]
    
    for room_data in initial_rooms:
        Room.objects.create(**room_data)

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_room'),
    ]
    
    operations = [
        migrations.RunPython(create_initial_rooms),
    ]
