# Generated by Django 5.2.1 on 2025-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='room',
        ),
        migrations.AddField(
            model_name='document',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('contract', 'Договор аренды'), ('invoice', 'Счет на оплату'), ('act', 'Акт оказанных услуг')], max_length=20),
        ),
    ]
