# Generated by Django 5.2.1 on 2025-06-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_document_room_document_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='document',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счет'), ('act', 'Акт')], max_length=20),
        ),
    ]
